config/routes.rb
Stm::Application.routes.draw do

  scope :module => :web do
    root :to => "welcome#index"

    resources :users
    resource :session, :only => [:new, :create, :destroy]

    resources :stories do
      scope :module => :stories do
	      resources :comments
      end
    end

  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	attr_accessible :title, :body

	belongs_to :user
	belongs_to :story

end

app/models/story.rb
class Story < ActiveRecord::Base

	belongs_to :owner,  :class_name => "User"
	belongs_to :executor, :class_name => "User"

	has_many  :comments

	attr_accessible :title, :description, :executor_id, :state_event

	validates :title, :presence => true,
										:length => { :maximum => 256 }
	validates :description, :presence => true
	validates :executor, :presence => true

	state_machine :state, :initial => :new do

		state :new
		state :started
		state :finished
		state :reopened
		state :accepted

		event :start do
			transition :new => :started
		end

		event :finish do
			transition [:started, :reopened] => :finished
		end

		event :reopen do
			transition :finished => :reopened
		end

		event :accept do
			transition :finished => :accepted
		end

	end

	def to_s
		title
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many  :stories, :dependent => :destroy,
	                    :foreign_key => "owner_id"

	has_many  :tasks, :class_name => "Story",
	                  :dependent => :nullify,
	                  :foreign_key => "executor_id"

	has_many  :comments,  :inverse_of => :user,
	                      :dependent => :destroy


  validates :password,  :presence => true,
												:on => :create

	validates :email, :uniqueness => true

  attr_accessible :email, :name, :password,:password_confirmation, :surname

	def full_name
		"#{name} #{surname}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController

	include AuthHelper

end

app/controllers/web/protected_controller.rb
class Web::ProtectedController < Web::ApplicationController

	before_filter :require_login

end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController

	def new
		@user = User.new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      user_sign_in(user)
      redirect_to root_url, :notice => "Logged in!"
    else
	    @user = User.new(params[:user])
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

	def destroy
		user_sign_out
		redirect_to root_url
	end

end

app/controllers/web/stories/application_controller.rb
class Web::Stories::ApplicationController < Web::ProtectedController
	 private

	def resource_story
		Story.find(params[:story_id])
	end
end

app/controllers/web/stories/comments_controller.rb
class Web::Stories::CommentsController < Web::Stories::ApplicationController
  def new
	  @story = resource_story
  end

  def create
	  story = resource_story
	  comment = story.comments.new(params[:comment])
	  comment.user = current_user
	  if comment.save
		  redirect_to story_path story, :notice => "Comment added"
	  else
		  flash.now.alert "Smth went wrong"
		  render story_path story
	  end
  end

end

app/controllers/web/stories_controller.rb
class Web::StoriesController < Web::ProtectedController
  def new
	  @story = Story.new
  end

  def create
	  @story = Story.new(params[:story])
	  @story.owner = current_user
	  if @story.save
		  redirect_to stories_path, :notice => "Story created"
	  else
		  render "new"
	  end
  end

  def index
	  @stories = Story.all
  end

	def show
		@story = Story.find(params[:id])
		@comment = @story.comments.build
	end

	def edit
		show
	end

	def update
		@story = Story.find(params[:id])
		if @story.update_attributes(params[:story])
			redirect_to story_path(@story), :notice => "Successfully updated"
		else
			flash.now.alert "Smth went wrong"
			render "edit"
		end
	end

end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ProtectedController

  def index
    @users = User.all
  end

  def new
   @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path @user, :notice => "Signed up!"
    else
      render "new"
    end
  end

	def show
		@user = User.find(params[:id])
	end

	def edit
		show
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to user_path @user
		else
			flash.now.alert = "Smth went wrong"
			render "edit"
		end
	end

end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

app/helpers/web/stories/comments_helper.rb
module Web::Stories::CommentsHelper
end

app/helpers/web/stories_helper.rb
module Web::StoriesHelper
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/helpers/web/welcome_helper.rb
module Web::WelcomeHelper
end

app/views/layouts/application.html.haml
%html
  %head
    = render 'layouts/shared/head'
  %body
    = render 'layouts/shared/navbar'
    .container
      .content
        = flash_block
        = yield

app/views/layouts/shared/_head.html.haml
%meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
%meta(charset="utf-8")
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%title= "Simple Task Manager"
= csrf_meta_tags
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"

app/views/layouts/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        %li= link_to "Home", root_url
        - if !current_user
          %li= link_to "Log In", new_session_path
        - else
          %li= link_to "Stories", stories_path
          %li= link_to "Users", users_path
          %li= link_to "Log Out", session_path, :method => :delete

app/views/web/stories/_comments.html.haml
%hr
.row
  .span2
    %strong Comments
    %hr
    %p
    - object.each do |item|
      .span4
      - if item.user.present?
        %p= item.user.full_name
      %p
        %strong= item.title
      .span4
      %p= item.body
      %hr

app/views/web/stories/_form.html.haml
=form.input :title
=form.input :description
=form.input :state_event, :as => :state_event
=form.association :executor, :prompt => "Choose an executor"
.controls= form.submit

app/views/web/stories/comments/_comments.html.haml
%hr
.row
  .span2
    %strong Comments
    %p
    - comments.each do |item|
      .span4
      %p= item.user.full_name
      wrights:
      %p
        %strong= item.title
      .span4
      %p= item.body
      %hr

app/views/web/stories/comments/_form.html.haml
= form.input :title
= form.input :body
.controls= form.submit "Comment"

app/views/web/stories/comments/new.html.haml
= simple_form_for [@story, @story.comments.new] do |form|
  = render "form", :form => form

app/views/web/stories/edit.html.haml
= simple_form_for @story do |form|
  = render "form", :form => form

app/views/web/stories/index.html.haml
%h2 Stories
%p= link_to "Add", new_story_path
%table.table.table-stripped.table-bordered.table-condensed
  %thead
    %tr
      %th= Story.human_attribute_name :id
      %th= Story.human_attribute_name :title
      %th= Story.human_attribute_name :description
      %th= Story.human_attribute_name :state
      %th Actions
  %tbody
    - @stories.each do |story|
      %tr
        %td= link_to story.id, story_path(story)
        %td= story
        %td= story.description
        %td= story.state
        %td= link_to "Edit", edit_story_path(story)

app/views/web/stories/new.html.haml
= simple_form_for @story, :url => :stories do |form|
  = render 'form', :form => form

app/views/web/stories/show.html.haml
.row
  .span2
    %strong= Story.human_attribute_name :title
  .span2= @story
.row
  .span2
    %strong= Story.human_attribute_name :description
  .span2= @story.description
.row
  .span2
    %strong= Story.human_attribute_name :state
  .span2= @story.state
.row
  .span2
    %strong= Story.human_attribute_name :owner
  .span2= @story.owner.full_name
.row
  .span2
    %strong= Story.human_attribute_name :executor
  .span2= @story.executor.full_name
= render "comments", :object => @story.comments
= simple_form_for [@story, @comment] do |form|
  = render "web/stories/comments/form", :form => form

app/views/web/users/_form.html.haml
= form.input :name
= form.input :surname
= form.input :email, :as => :email
= form.input :password
= form.input :password_confirmation
.controls= form.button :submit, "Submit"

app/views/web/users/edit.html.haml
= simple_form_for @user do |form|
  = render "form", :form => form

app/views/web/users/index.html.haml
%table.table.table-stripped.table-bordered.table-condensed
  %thead
    %tr
      %th= User.human_attribute_name :id
      %th= User.human_attribute_name :name
      %th= User.human_attribute_name :surname
      %th= User.human_attribute_name :email
      %th Actions
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user.id)
        %td= user.name
        %td= user.surname
        %td= user.email
        %td= link_to "Edit", edit_user_path(user.id)

app/views/web/users/new.html.haml
= simple_form_for @user, :url => :users do |form|
  = render 'form', :form => form

app/views/web/users/show.html.haml
.row
  .span2
    %strong= User.human_attribute_name :name
    \:
  .span2= @user.full_name
.row
  .span2
    %strong= User.human_attribute_name :email
    \:
  .span2= @user.email

app/views/web/welcome/index.html.haml
%h2= "#{current_user.full_name}, welcome to Simple Task Manager"